# Tensorflow - AAT notes

## import libraries

In [1]:
import tensorflow as tf
import numpy as np

print("TensorFlow version: ",tf.version.VERSION)

TensorFlow version:  2.3.0


tensors

In [2]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [4]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


### convet Tensor to numpy array



In [5]:
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [6]:
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

variables

operations

Slicing

indexing

creatin N dimentional tensors

features

reading writing files - serialization

Tf messages

TFrecords

writing files - serializing

reading serialized files

CSV


In [ ]:
#code here

#references

## gitgub

https://github.com/googlecloudplatform/training-data-analyst



## intro to tensorflow - coursera

https://github.com/GoogleCloudPlatform/training-data-analyst/tree/master/courses/machine_learning/deepdive2/introduction_to_tensorflow















